name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node
      uses: actions/setup-node@v1
    - name: npm install, build, and test
      run: |
        yarn install --frozen-lockfile
        # npm ci
        # npm run build --if-present
        yarn test
      env:
        CI: true
